# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: o:/New folder/IP_FIR_FILTER/create_ip_with_sysgen/create_ip_with_sysgen.srcs/sources_1/ip/fir_filter_0/fir_filter_0.xci
# IP: The module: 'fir_filter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: o:/New folder/IP_FIR_FILTER/create_ip_with_sysgen/create_ip_with_sysgen.srcs/sources_1/ip/fir_filter_0/fir_filter_fir_compiler_v7_2_i0/fir_filter_fir_compiler_v7_2_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_filter_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fir_filter_fir_compiler_v7_2_i0} -quiet] -quiet

# XDC: o:/New folder/IP_FIR_FILTER/create_ip_with_sysgen/create_ip_with_sysgen.srcs/sources_1/ip/fir_filter_0/fir_filter_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_filter_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fir_filter_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/New folder/IP_FIR_FILTER/create_ip_with_sysgen/create_ip_with_sysgen.srcs/sources_1/ip/fir_filter_0/constrs/fir_filter.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: o:/New folder/IP_FIR_FILTER/create_ip_with_sysgen/create_ip_with_sysgen.srcs/sources_1/ip/fir_filter_0/fir_filter_0.xci
# IP: The module: 'fir_filter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: o:/New folder/IP_FIR_FILTER/create_ip_with_sysgen/create_ip_with_sysgen.srcs/sources_1/ip/fir_filter_0/fir_filter_fir_compiler_v7_2_i0/fir_filter_fir_compiler_v7_2_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_filter_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fir_filter_fir_compiler_v7_2_i0} -quiet] -quiet

# XDC: o:/New folder/IP_FIR_FILTER/create_ip_with_sysgen/create_ip_with_sysgen.srcs/sources_1/ip/fir_filter_0/fir_filter_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_filter_fir_compiler_v7_2_i0 || ORIG_REF_NAME==fir_filter_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/New folder/IP_FIR_FILTER/create_ip_with_sysgen/create_ip_with_sysgen.srcs/sources_1/ip/fir_filter_0/constrs/fir_filter.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_filter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
